### ISSUE TITLE
CPU부하 방지 및 서버 전체 API요청 속도개선 처리를 위한 ALB(Application-Load Balancer) 도입

### ISSUE THREAD

**Issue by iswoos** [OnNaNOn/OMG#160]
### 💡 이슈 내용
> 1.  단일 서버로 운영할 시에 벌어지는 문제 (CPU 부하) 상황을 가정하여, 트러블 슈팅안을 아래 개설하였음(https://desirelsw.tistory.com/170)

### 🔎 문제 분석
> 1. 현재 프로젝트는 일 평균 사용자가 10만명인 상태임. 이를 단일 서버로만 운영할 시에 CPU부하가 일어나 서버에 대한 전체 API요청에 대한 속도가 저하될 것이 우려됨

### ✅ 작업 내용
> 1. ALB (Application-Load-Balancing)을 도입하여, 전체 API요청 응답속도를 개선할 예정임
(https://desirelsw.tistory.com/172)

### 🚨 주의 사항
> 없음

**Comment by ahn-sj** [comment]
#166 #167 
기존 1700만건에 대한 상품 데이터의 조회 API의 성능면에서 44s라는 너무 많은 시간이 소요돼서, Full Text Search를 도입하여 현재 1056ms의 응답을 받도록 개선했습니다!

![image](https://user-images.githubusercontent.com/64416833/204603081-8a2b5921-ab72-4807-8c79-94d6a4fe31b7.png)

**Comment by ahn-sj** [comment]
#173 
상품 17,400,006건에 대해 QueryDSL-JPA, Full Text Search,  Full Text Search With Covering Index 성능 비교 완료했습니다.

**Comment by iswoos** [comment]
main replication(DB 이중화) 구현완료하였습니다. 
헌데 Full Text Search 파일과 일부 충돌이 일어나고 있어, 별도로 설정파일을 조율해주실 수 있는지 문의드립니다!!


![image](https://user-images.githubusercontent.com/102216495/204977687-02bfc8df-7414-4f46-a92e-239ad9e9e409.png)

**Comment by iswoos** [comment]
### 🚨 주의 사항
> 페이지네이션 이상이 생겨, 후속 조치 필요함

상황 : 1 -> 2 페이지와 같이, 바로 다음 페이지로 이동하기가 불가능한 상태

![image](https://user-images.githubusercontent.com/102216495/204981019-7acd5f34-b4d0-4ab9-979c-8c5f691747cf.png)

**Comment by iswoos** [comment]
현재 부하테스트로 유저 3,000명이 1회씩 요청을 하였을 경우 서버가 터진 현상이 발생하였음

로드밸런서 도입을 해야하는 추가 이유가 생김

![image](https://user-images.githubusercontent.com/102216495/204997018-6f9a4516-caf8-4417-945a-17d0d35e7471.png)
