### ISSUE TITLE
I/O부하 방지를 위한 DB이중화 (main-replication) 도입

### ISSUE THREAD

**Issue by iswoos** [OnNaNOn/OMG#178]
### 💡 이슈 내용
> 1.  단일 DB로 운영할 시에 벌어지는 문제 (I/O부하)에 대한 해결방안이 필요하다.

### 🔎 문제 분석
> 1. 현재 프로젝트 목표 사용자수는 일 평균 10만명임. 이를 단일 DB로만 운영할 시에 I/O부하가 일어나 추후 DB응답속도가 저하될 것이 우려됨

### ✅ 작업 내용
> 1. main-replication 구조로 DB이중화를 시켜, I/O부하를 방지할 예정

### 🚨 주의 사항
> 없음

**Comment by iswoos** [comment]
### 🚨 문제상황

> 현재 DB이중화는 완료하였으나, 이벤트 상품에 대한 대규모 고객주문 상황을 시나리오로 테스트 해봤을 때 동시성 제어가 되지않아 데이터 정합성이 맞지않는 상황 발생함. 이에 따른 처리가 필요함

![image](https://user-images.githubusercontent.com/102216495/205051689-c1f7900a-1084-4212-9a63-b7c48556b861.png)

**Comment by ahn-sj** [comment]
현재 Master-Slave 도입 완료 후 테스트 시 적은량의 데이터에 대해 정상 동작하는 걸 확인했습니다. 아래 링크를 참고해주세요!
단, JMeter 기준으로 사용자의 수가 약 200건이 넘어가는 시점부터 정합성이 맞지 않는 문제가 있습니다.

제 생각에 최대 쓰레드 풀 개수를 제한하는 것이 좋다고 생각돼서 내일 이것과 관련된 내용을 추가 도입하여 실행 결과에 대한 코멘트 남기겠습니다.

https://github.com/ahn-sj/mysql-master-slave#%EC%8B%A4%ED%96%89%EA%B2%B0%EA%B3%BC

**Comment by ahn-sj** [comment]
쓰레드의 최대 개수를 제한한 결과 비관적 락으로 테스트한 결과 초당 57~64개의 Request를 32초간 2천개의 요청을 보냈을 때 정상적인 결과가 나옴을 확인했습니다.

- JMeter TPS (Pessimistic Lock)
![image](https://user-images.githubusercontent.com/64416833/205201259-764dbb45-4e8a-4903-8868-28b3407b6cc1.png)

- Spring Boot Console
![image](https://user-images.githubusercontent.com/64416833/205201394-c751cddd-9b31-494b-b974-84e8e9c5a198.png)

---

반면 동일한 조건으로 Redis의 Redisson으로 테스트한 결과 정상적으로 2천개의 재고가 감소되는 것은 확인했으나, 비관적 락에 비해 처리되는 속도가 현저히 느렸습니다. 동일 조건에서 초당 18~24개의 Request가 처리되었고, 89초만에 2천개의 요청에 대한 응답이 완료되었습니다.

tryLock의 조건은 다음과 같습니다.
`lock.tryLock(10, 5, TimeUnit.SECONDS)`

- JMeter TPS (Pessimistic Lock)
![image](https://user-images.githubusercontent.com/64416833/205203089-ba688af0-2fb2-47f1-abc5-1994713dd844.png)

- Spring Boot Console
![image](https://user-images.githubusercontent.com/64416833/205203145-af88836c-53a8-4a39-a48b-c45e362db3e2.png)

현재 DB Replication이 적용되긴 했으나 결국 CUD(Create, Update, Delete)에 대한 처리는 Master DB에서 처리되기 때문에 Redis 도입없이도 처리 가능하다는 점과 속도적인 측면에서도 비관적 락이 더 괜찮다고 생각됩니다.

**Comment by iswoos** [comment]
현재 아래 이미지와 같이 @Transactional 처리만 해주었기 때문에 
main DB에서만 처리가 가능합니다!

![image](https://user-images.githubusercontent.com/102216495/205224440-4a9697bb-e91e-4599-a18f-a160a1b286eb.png)


이 덕분에
- 비관적 락으로 처리가능
- 동시성 제어

두 가지 모두 가능해진 것으로 확인됩니다.
접속자 수를 제한하는 것이 조금 아쉬우나, 더 발전시킬 수 있는 방향이 있는지 저도 찾아보도록 하겠습니다!

**Comment by ahn-sj** [comment]
현재 DB 다중화(Master-Slave) 도입이 정상적으로 되었기에 Close 처리 해놓겠습니다.
만약, 문제되는 사항이 생길 시 ReOpen 부탁드립니다!
