### ISSUE TITLE
ERD 변경

### ISSUE THREAD

**Issue by ahn-sj** [OnNaNOn/OMG#27]
기존 테이블에서 쿠폰 도메인과 연관관계, 필드 추가의 이유로 ERD가 변경되었다. 변동사항은 다음과 같다.

- 공통
1. 각각의 도메인의 기능에 따라 YN필드를 두어 UPDATE로 삭제 유무를 판단한다.
해당 필드명은 private String isDeleted로 통일하고 삭제되지 않은 경우에 "N"값을 저장하고 삭제된 경우 "Y"값을 저장한다.
2. 연관관계의 변경과 추가된 필드들에 대해 본인이 맡은 도메인을 변경한다.

![Copy of ONO COM](https://user-images.githubusercontent.com/64416833/201960787-9ad94ea5-b355-4f72-a025-5f19a83799e2.png)

========

!!필독!!
완료된 경우 Comment에 완료 메시지와 Commit Number를 기입하기

**Comment by ahn-sj** [comment]
이미지가 들어가야하는 도메인의 필드명은 다음과 같다. `private String imgUrl`

**Comment by ahn-sj** [comment]
#35 Feat: Add isDeleted Field And Event <-> Product Associated relationship
isDeleted 필드 추가 및 연관관계 변경 완료

**Comment by iswoos** [comment]
**[처리 완료사항]**
1. 이미지 들어가야하는 도메인 필드 추가 완료
2. isDeleted 필드 추가 및 연관관계 변경 완료
