### ISSUE TITLE
재고 관리와 그에 따른 동시성 고려

### ISSUE THREAD

**Issue by ahn-sj** [OnNaNOn/OMG#28]
재고 관리와 관련해서 동시성을 고려해야 할 상황이 생겼다.
일단 동시성과 관련된 키워드로 Synchronized, Lock 애노테이션, Redis가 있고, 상황과 규모에 따라 필요한 기술을 도입할 예정이다.

고려하게 된 상황에 대한 시나리오는 다음과 같다.
> Ex) N월 N주차 N요일 N시에 1000명 한정 치킨 선착순 이벤트 (스케줄링)
> TOP 1 >> 치킨 100, TOP 10 >> 치킨 1000, TOP 100 >> 치킨 10000

선착순과 더불어 고려해야 하는 것은 주문 취소 시에 대한 것이다.
이것과 관련해서 우리 서비스만의 정책을 정해야 할 것 같다는 생각이 들었다.

만약 특정 제품에 대한 재고 수량이 소진된 경우 배송 전 or 상품 준비중 or 환불 등의 과정에서 취소가 발생할 경우 재고를 +1을 해줄지 또는 유지를 할지에 대해 정책을 정해야 하는데 각각의 의견을 자유롭게 남겨주시면 감사하겠습니다.

**Comment by ahn-sj** [comment]
비관적 락의 단점으로 트래픽이 증가할 경우 부하가 크다는 문제가 있어서 분산 DB를 도입하는 것도 방법이라 생각했지만 우리 서비스의 규모에 과도한 비용이 들 것 같다는 생각에 분산 DB는 고려하지 않기로 결정됨

**Comment by ahn-sj** [comment]
우리 서비스의 목적과 비슷한 동시성과 관련 강의를 팀 지원금으로 구매하기로 결정

[인프런] 최상용 님 - 재고시스템으로 알아보는 동시성이슈 해결방법
https://inf.run/CCku

**Comment by iswoos** [comment]
**동시성 제어관련 코드는 모두 완료되었습니다.** 
Synchronized, Lock 애노테이션, Redis 등, 다양한 방법론들이 있었으나
이슈번호 #22 에 기재된 이유에 따라, Redisson을 도입하여 문제를 해결하였습니다. 

다음 토의 때 시나리오가 명확히 정해지면, 시나리오 조건에 따라 로직을 추가로 변경하도록 하겠습니다.
