### ISSUE TITLE
2022.11.18(금), 11.19(토) 오전 예정

### ISSUE THREAD

**Issue by ahn-sj** [OnNaNOn/OMG#54]
== 완료 ==
1. API 명세서, ERD, 와이어프레임 수정 - **_11.18 완료_**

2. 코드 개선점 확인 - **_11.18 완료_**

3. 동시성 구현 완료로 JMeter로 부하테스트 진행(댓글 참고) - **_11.18 완료_**

4. 더미 데이터(Python) 코드 작성 - **_11.18 완료_**

5. 배포 (18일 자정까지 한 작업에 대한 건 배포해서 정상 작동 확인 완료) - **_11.19 완료_**
배포 시 Logging되기 때문에 로그레벨 및 편의성 로그 기능 OFF

6. View 완성 
메인 페이지 페이지네이션 기능 추가 - **_11.18 완료_**

== 예정 ==
7. 테스트 코드 작성

8. View 완성 
  - 토큰을 Local Storage에 저장은 가능하지만 ajax와 SSR 동시사용 불가능으로 인해 SSR 형태인 건 MVP 이후에 진행될 예정
  - 메인 페이지, 재고관리 페이지에 검색 기능 추가 (동적쿼리는 회의를 진행하고 결정)

**Comment by ahn-sj** [comment]
#53 너무 늦게 잠들어서 점심정도에 오겠습니다.....!

**Comment by iswoos** [comment]
이슈번호 #50 
현재 더미데이터는 작업 중에 있습니다.

**Comment by ahn-sj** [comment]
1. API 명세서, ERD 수정 완료

**Comment by ahn-sj** [comment]
> 이슈번호 #50 현재 더미데이터는 작업 중에 있습니다.

#59 @iswoos  : 더미데이터 (Python) 코드 작성 완료

**Comment by ahn-sj** [comment]
3. 동시성 구현 완료로 JMeter로 부하테스트 진행

  - 환경 설정

![image](https://user-images.githubusercontent.com/64416833/202675532-6531ed6a-3391-42ef-ae0b-7f36c8ae81fc.png)

  - 성능 테스트 결과

![image](https://user-images.githubusercontent.com/64416833/202675905-52e96abf-5426-45b3-997c-910c2c1ea030.png)

**Comment by iswoos** [comment]
**[MVP 중간발표 피드백사항]**

1. 시나리오를 잘 뽑았다. 서비스 개발자로서 중요한 역량 및 감각을 키우게 된 것 같다.
2. 장바구니 및 창고재고는 기능 스코프에 따라 선택하는 것이다. (한번 시도 해보는 것도 좋다만, 주 포커스가 해당 사항이 아니라면 남은 3주동안에 투자할만한 우선순위인지 측량해보자)
3. 주요 기능에 대한 목적(목표지표)을 확실히 정하고 행동을 하자 (기술 나열에 그치지않고, 실제로 필요한 기능에 대해 생각해보고 그 기술을 도입하는 형식으로 해봐라!)
4. PM측면에서 생각해보는 습관을 들여라.(기술에 대한 현실적인 생각을 하자)
5. 부하테스트를 할 때 DB도 같이 바뀌는지도 확인하는 테스트도 있어야한다?
6. Swagger 문서화한 점, 어플리케이션단에서 모니터링, 회고 등등 칭찬!
7. 동시성 테스트에 있어서 작은 단위부터 시작하여 점점 크게 테스트를 가져간점. 좋은 접근방법이다.
8. 향후계획 방향성 확실히!
