### ISSUE TITLE
OnNaNOn 팀 3주차 설정목표 / 2022.11.19(토)

### ISSUE THREAD

**Issue by iswoos** [OnNaNOn/OMG#69]
프로젝트의 목적 및 목표에 더욱 집중하여 설계가 진행되면 좋을 것 같다는 의견이 저희 토의결과로 도출되었습니다.

이에 따라 진행예정 및 향후 예상작업 리스트를 산출하였습니다.
디테일한 사항은 논의 후 추가로 기재될 예정입니다!

**== 진행예정 ==**
1. 테스트 코드 작성
2. View 완성
토큰을 Local Storage에 저장은 가능하지만 ajax와 SSR 동시사용 불가능으로 인해 SSR 형태인 건 MVP 이후에 진행될 예정
메인 페이지, 재고관리 페이지에 검색 기능 추가 (동적쿼리는 회의를 진행하고 결정)

**== 향후 예상작업 리스트 ==**
1. 프로젝트 세부 목표 설정 (기능 구체화)
2. 목표에 따른 기술선택 및 도입 (필요성에 대한 고민필수)
3. 기술 도입 시, 예상되는 문제에 대한 시나리오 설계 및 대응방안 구축
4. Swagger를 Spring Rest Docs로 대체 + 테스트 커버리지 95%이상 달성 (필요성에 대한 논의는 추가적으로 할 예정) 
5. CI/CD 도입 (github 액션배포 사용예정)
6. 헬스체킹을 위한 Actuator 도입 및 log 실시간 모니터링 도구 도입
7. 필요 API 추가증설

**== 마감 예정기한 ==** 
2022.11.25(금)

**Comment by iswoos** [comment]
**향후 예상작업 리스트**의 1번사항인 프로젝트 세부 목표설정이 최우선과제. 
2022.11.21(월) 09:00에 회의할 예정

**Comment by ahn-sj** [comment]
2주차도 정말 고생 많으셨습니다. 3주차도 화이팅입니다!!

**Comment by ahn-sj** [comment]
CI/CD에 대한 건 잘 모르지만 CI/CD가 적용이 되면 브랜치 전략을 다음과 같이 바꿔보는 건 어떤지 의견을 듣고 싶습니다.

현재는 각자의 브랜치에서 작업한 후 master(main) 브랜치로 PR과 Merge를 날리지만 이렇게 될 경우 테스트를 거쳐야 실행되긴 해도 추가적인 검증 및 테스트를 거치면 좋을 것 같아서 develop 브랜치를 추가해서 테스트가 완료되고나면 master(main)에 merge하는 식의 전략으로 구성하는건 어떤가요?

또한, develop 브랜치 추가가 되면 머지(Merge)전에 동료평가(Peer Review)를 거친 다음에 병합하는 것도 추가되면 좋을 것 같습니다!!!

**Comment by ahn-sj** [comment]
> 

저희가 예정하는 로깅 모니터링 구축과 관련해서 도움될 만한 사이트를 발견해서 공유합니다.
https://jongmin92.github.io/2019/12/04/Spring/prometheus/

**Comment by ahn-sj** [comment]
3주차 역할 분담
이승우 님
- CI/CD + AWS + RDS

전성영 님
- 로깅과 실시간 모니터링 도입
- (필수X) Webhook을 이용한 알림 발송

안성재 님
- Spring REST Docs + 테스트 커버리지 95% 이상(jacoco) + 테스트 코드
-

**Comment by ahn-sj** [comment]
이벤트 기능 관련 투두 리스트

담당: 이승우 님
블랙프라이데이 매일 18:00 선착순 특가 이벤트, (22.11.23(수) ~ 22.11.30(수))
예상 이벤트 : 100개 한정 에어팟 5천원 선착순 판매이벤트
예상 시나리오 : 10,000명 동시 구매현상 발생 + 동시 접속자수 10,000명
예상기술 : 스케줄러, 동시성(Redisson)

담당: 전성영 님
마이페이지 조회 시, 주문내역 노출 (주문내역, 상품등록내역, 좋아요내역, 리뷰내역)
조건
특정 사용자에 의해 올라온 것만 조회
주문 내역과, 상품 등록 내역은 페이징 // 좋아요 내역과 리뷰 내역은 수정날짜 기준 10개의 데이터(TOP 10)만
+ 메인 페이지 검색 기능 ()

담당: 안성재 님
thymeleaf, ajax, jQuery로 View단을 구현 완료
(인증/인가에 대한 처리(사용자의 등급은 일반, 구독자, 관리자로 구성)를 위해 Request Header에 Token을 추가해줄 필요가 있어서 차주부터 ajax로 페이지를 구성할 예정)

재고 관리 페이지 검색 기능

**Comment by iswoos** [comment]
이벤트 관련 핵심기능은 구현해놓았습니다!  #77
논의사항이 결정되면 마무리 짓도록 하겠습니다.

**Comment by ahn-sj** [comment]
thymeleaf, ajax, jQuery로 View단을 구현 완료
(인증/인가에 대한 처리(사용자의 등급은 일반, 구독자, 관리자로 구성)를 위해 Request Header에 Token을 추가해줄 필요가 있어서 차주부터 ajax로 페이지를 구성할 예정)
============
페이징과 토큰을 포함해서 thymeleaf To ajax로 구현 완료했습니다.
내일 검색 기능까지 추가하겠습니다.

**Comment by ahn-sj** [comment]
진행상황(22.11.23) 및 진행 예정(22.11.24)
**전성영 님**
1. 진행 상황
View 90% 구현 완료 (마이페이지, 리뷰 기능은 후순위)

2. 진행 예정
헬스체킹 도입 및 모니터링 툴 조사

====================

**이승우 님**
1. 진행 상황
AWS + RDS + S3 + CI/CD (보류,  Github Actions / AWS Code Deploy)

2. 진행 예정
- 이벤트 기능 구현 (특정 시간에 이벤트 생성)
- 테스트 코드 

추가
- Product Entity 생성자
- RedissonLockStockFacadeTest

====================

**안성재 님**
1. 진행 상황


2. 진행 예정

**Comment by ahn-sj** [comment]
주문과 상품에 대한 테스트 코드는 내일 체크인하고 바로 수정해놓겠습니다.

![image](https://user-images.githubusercontent.com/64416833/203647403-f1bd146d-6072-4808-b488-3e022d38117a.png)

**Comment by ahn-sj** [comment]
테스트 실패했던 코드들에 대한 수정 및 여러 기능들에 대한 테스트 완료했습니다.

Refer: #147 Test: Edit And Add Test Code 100% Successful in Local MySQL 

![image](https://user-images.githubusercontent.com/64416833/203775313-4bdf8b98-83dd-4893-bc81-bb84e2f6d6ad.png)

**Comment by ahn-sj** [comment]
3주차가 지난 관계로 Issue Close 하겠습니다
