### ISSUE TITLE
Method Naming

### ISSUE THREAD

**Issue by ahn-sj** [OnNaNOn/OMG#70]
#68 메서드명 관련해서 valid와 같은 키워드를 붙여서 조금 더 명확한 네이밍을 할 수 있도록 수정해보는 건 어떨까요!?
https://github.com/OnNaNOn/OMG/commit/60677d8e31e19f1fa25cfc5462e0a8db9f665b46#r90427199

**Comment by iswoos** [comment]
넵! 좋은 것 같습니다. 
요청주신 내용은 아래와 같은 사항을 의미해주신 것인지 체크 부탁드립니다.

[기존 메소드명]
getAccount

[변경희망 메소드명1]
validAccount

[변경희망 메소드명2]
checkAccountValid

**Comment by ahn-sj** [comment]
[변경희망 메서드명1] 로 변경을 해주시면 너무 감사할 것 같습니다. 수용해주셔서 감사합니다.


메서드 네이밍 관련해서 추가로 참고해볼만한 사이트도 첨부합니다.
1. [[캠퍼스 핵데이 Java 코딩 컨벤션]] 2.10. 메서드 이름은 동사/전치사로 시작
https://naver.github.io/hackday-conventions-java/#method-verb-preposition

2. [[tecoble]] 메서드 이름으로 자주 사용되는 동사
https://tecoble.techcourse.co.kr/post/2020-04-26-Method-Naming/

===========

수정과 머지가 완료되면 Issue Close 해주시면 감사하겠습니다!!

**Comment by iswoos** [comment]
넵! 내용 공유감사드립니다 ㅎㅎㅎ

표현을 항상 못하고있지만
이번 프로젝트를 같이 하게돼서 너무 만족스럽습니다.
남은 기간도 같이 힘내서 좋은 결과 내보길 바랍니다.

파이팅입니다 우리!
