### ISSUE TITLE
브랜치 전략수립

### ISSUE THREAD

**Issue by iswoos** [OnNaNOn/OMG#75]
### 💡 이슈 내용
> 현재 운영 중인 브랜치 전략보다 더 구체화되고 세밀한 구조를 만들어야 할 필요성을 느낌

### ✅ 작업 내용
> 토의를 거친 뒤, 적합한 브랜치 전략으로 기존 브랜치 변경할 예정

### 🚨 주의 사항
> 없음 (기존 데이터 날아가지 않게만 조심하면 될 듯!)

**Comment by iswoos** [comment]
**[현 상황]**

현재 CI/CD는 main 브랜치에 pull_requests가 될 경우 작동하게끔 설정 되어있습니다.
그러니 아래와 같은 브랜치 전략은 어떠신지 문의드립니다!

**[제안 사항]**
> 최종브랜치
- main

> 기술종합브랜치(dev)
- dev

> 개인 기술브랜치(dev)
- ahndev
- jundev
- leedev

**[제안 이유]**
main브랜치에는 dev에 종합된 안전한 내용들만 pull_requests되게끔 설정하여 CI/CD가 일시중지 되지않도록 하기위함.


충분히 충족되는 제안 내용은 아닐 것으로 생각됩니다.
허나 가감없는 피드백을 주시면 더욱 좋은 방향으로 개선할 수 있을 것 같습니다!
@ahn-sj @junsj119 님, 편안히 의견 내주시면 감사하겠습니다!

**Comment by ahn-sj** [comment]
우선 멘션을 달아주셨지만 이제야 확인된 점 죄송합니다.
Feature 브랜치까지 추가하는 것이 좋은 브랜치 전략이 될 것 같지만 현재로서 CI/CD가 도입되었기 때문에 일단은 develop 브랜치를 두고 해당 브랜치에 기존에 main 브랜치에 merge를 했던 것처럼 해도 괜찮을 것 같습니다!!

의견 주셔서 감사합니다!
