### ISSUE TITLE
Spring Scheduler 처리

### ISSUE THREAD

**Issue by iswoos** [OnNaNOn/OMG#77]
### 💡 이슈 내용
> 1. 블랙프라이데이 컨셉으로 프로젝트를 진행 중 
> 2. 컨셉에 맞게, 매일 18:00시 선착순 특가 이벤트 기능을 구현할 예정
> 3. 이를 위해 매일 18:00시에 에어팟 100개를 판매가 5천원 한정재고로 생성할 예정

### ✅ 작업 내용
> Spring Scheduler를 이용하여 매일 18:00시에 상품이 생성되게끔 진행할 예정

### 🚨 주의 사항
> 없음

**Comment by iswoos** [comment]
### ✅ 진행상황
> 21일 ~ 30일 기준, 매일 2시 50분에 상품이 생성되도록 테스트 해본 결과, 서버에 되는 것 확인완료. 디테일한 사항은 점차 개선할 예정임

![image](https://user-images.githubusercontent.com/102216495/202975619-65d0c636-3ffb-483a-9c5e-6b1257afd4a1.png)

![image](https://user-images.githubusercontent.com/102216495/202975631-01fc2c12-d26e-4c51-9fea-26ad0f70e78e.png)

**Comment by ahn-sj** [comment]
#167 현재 팀원 모두가 접속하는 14:00로 스케줄링이 동작되도록 변경시켰습니다.
상품 및 이벤트 생성과 스케줄링을 연동하고 상세페이지에서 주문이 완료되는 것까지 구현 마쳤습니다.

**Comment by iswoos** [comment]
이벤트 생성 스케줄러 구동 확인완료 하였습니다
이슈 클로즈하겠습니다!

**Comment by iswoos** [comment]
### 💡 이슈 내용
> 1. ubuntu 서버의 Timezone이 UTC로 설정되어있어 이벤트 스케줄러로 상품 생성 시 이벤트 시작일 및 종료일의 date가 UTC시간대로 노출되고 있음

**[코드내용]**
```
@Scheduled(cron = "0 07 14 * * *") // 21-30일까지 02시 13분 55초에 스케줄 동작 >> cron = "55 13 02 21-30 * *"
    public void createEvent() {
        Product savedProduct = productRepository.save(new Product("에어팟 프로2", 4990, "이벤트 상품", "초고속 배송", 5000, 1L));
        LocalDateTime now = LocalDateTime.now();

        eventRepository.saveAndFlush(new Event(savedProduct.getId(), "매일 매일 쏟아지는 에어팟!", "야 나두", now, now.plusDays(1)));
    }

```

![image](https://user-images.githubusercontent.com/102216495/205422272-24a138c0-2bdc-46b0-82d5-5d4ca457a591.png)


### ✅ 작업 내용
> ubuntu server의 Timezone을 KST기준으로 변경


```
$sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
$date
Mon Nov 28 19:47:12 KST 2022
```

해당 코드로 시스템 시각을 변경함으로써, 이벤트 시작일 및 종료일을 KST기준으로 명시할 수 있게 되었다.

**[기존 시스템 시각정보]**
```
$ timedatectl
               Local time: Thu 2022-12-01 07:40:14 UTC
           Universal time: Thu 2022-12-01 07:40:14 UTC
                 RTC time: Thu 2022-12-01 07:40:14
                Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

**[변경 시스템 시각정보]**
```
               Local time: Thu 2022-12-01 16:41:44 KST
           Universal time: Thu 2022-12-01 07:41:44 UTC
                 RTC time: Thu 2022-12-01 07:41:44
                Time zone: Asia/Seoul (KST, +0900)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

### 🚨 주의 사항
> 없음

**Comment by iswoos** [comment]
### 💡 이슈 내용
> 이벤트 상품 생성 시, 하드코딩이 구현되어 있어 유지보수에 좋지 않을 것이라고 판단됨

### 🔎 문제점 분석
> 1. 이벤트 전용 view단이 개설되지 않아 하드코딩된 부분이 없지않아 있음
> 2. 굳이 코드부분에서 이벤트 상품을 생성해야 하는 지, 그 효율성에 대한 의문점이 생김

### ✅ 작업 내용
> 관리자 계정으로 로그인할 시, view단에서 특정 상품을 별도로 이벤트 상품으로 생성시키는 기능을 구현하는 것이 적합하다고 판단. 이를 토대로 기능을 구현할 예정   

### 🚨 주의 사항
> 없음

**Comment by ahn-sj** [comment]
위 이슈에 대한 작업 내용은 다음과 같습니다.

## 문제점
상품과 이벤트에 대해 하드 코딩이 되어있다.

## 해결 방안
스케줄러를 사용하는 것은 동일하나, 구현의 방식을 변경

기존에는 하드 코딩된 상품에 대해 이벤트를 생성했던 것과 달리 새로운 방식은 입력된 값으로 상품을 생성하고 이벤트를 생성하는 방식으로 변경되었습니다.
1. 이벤트 생성(관리자 권한을 가진 사용자만 접근 및 등록 가능) 페이지에서 입력 값에 따른 요청을 서버로 보낼 경우 데이터베이스에 바로 반영이 되지만 `sold_type`이라는 값을 false로 두어 화면에는 표시하지 않도록 구현하였습니다.
2. 위 값이 변경되는 시점은 매일 18시와 01시로 각각 이벤트 Open, Close의 동작을 수행하게 됩니다.
*2번의 과정이 정상적으로 동작하기 위해서는 이벤트 등록일을 기준으로 이전의 날짜로 등록이 되지 않도록 하기 위해 입력란에서 선택하지 못하도록 Block 처리를 해두었습니다.
![image](https://user-images.githubusercontent.com/64416833/205816766-6eb62529-bc1a-4633-a97a-9bf345806031.png)

3. Open이 되는 기준은 이벤트 시작일자가 오늘 날짜 기준 +1일인 것이고, Close가 되는 기준은 이벤트 종료일자 +1일입니다. #200 

4. 3번에 이어지는 얘기로 당연히 이벤트 조회 기준은 sold_type이 true인 데이터만 읽어오게 됩니다.

## 추가 도입
위 사항대로 변경했을 경우의 문제점도 고려를 했습니다.
A. 이벤트의 sold_type이 true가 되고나서, 시작시간 전까지 약 30시간동안의 요청은 어떻게 할 것인가?
B. 이벤트 종료시간이 지나고 나서 sold_type이 false이 되기전까지의 시간동안 요청은 어떻게 할 것인가?

위 사항들에 대해 컨트롤러까지 넘어오기 전에 필터링 역할을 하는 **인터셉터**를 두는 방법을 생각해냈고, 구현이 완료되었습니다.

모든 주문에 대해 주문 경로인 confirm이 포함되어 있는지를 확인하고 포함되어 있다면, 상품번호로 이벤트 정보를 읽어온 다음 이벤트 시작 시간과 현재 시간을 compareTo로 비교하여 현재 시간이 이벤트 시작시간이후에만 접근이 가능하도록 구현했습니다.

이벤트 기능은 구현이 완료 되었고, 이에 따라 이슈 Close 처리 하겠습니다!!
